### ISSUE TITLE
Invalid option error for r6g.medium spot conversion

### ISSUE THREAD

**Issue by IvanNoronha-TomTom** [jcjorel/ec2-spot-converter#11]
@jcjorel  Perhaps it is due to the new instance type but when I tried converting an r6g.medium from on demand to spot it gave me this error
```
[INFO] 2021-08-29 08:01:06,276 ec2-spot-converter - [STEP 14/26] Terminate instance...
[INFO] 2021-08-29 08:01:06,424 ec2-spot-converter -   => SUCCESS. Successfully terminated instance i-08da23413cc50235a.
[INFO] 2021-08-29 08:01:06,442 ec2-spot-converter - [STEP 15/26] Wait resource release...
[INFO] 2021-08-29 08:01:06,635 ec2-spot-converter - Waiting for instance 'terminated' state...
[INFO] 2021-08-29 08:01:11,686 ec2-spot-converter - Waiting for instance 'terminated' state...
[INFO] 2021-08-29 08:01:18,748 ec2-spot-converter -   => SUCCESS. All resources released : ['eni-0315f33b44b37eade'].
[INFO] 2021-08-29 08:01:18,766 ec2-spot-converter - [STEP 16/26] Create new instance...
Traceback (most recent call last):
  File "./ec2-spot-converter", line 1570, in <module>
    sys.exit(main(sys.argv))
  File "./ec2-spot-converter", line 1536, in main
    return_code, reason, keys = step["Function"]()
  File "./ec2-spot-converter", line 953, in create_new_instance
    response = ec2_client.run_instances(**launch_specifications)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnsupportedOperation) when calling the RunInstances operation: The r6g.medium instance type does not support specifying CpuOptions.

```

Since the original instance is terminated is there a quick way to roll back? Or I will need to re-create the machine from backed up AMI

**Comment by jcjorel** [comment]
Hi,
Thanks for reporting this issue.
Currently, the tool has been tested only on Intel/AMD instance types: You highlighted the need to test it against Graviton types.

I'm going to release a fix very soon (=next day hopefully). if you can sustain to wait, the new version will be able to continue the conversion where it was stopped. If you can not wait, indeed, you have to restore from the Backup AMI.

**Comment by IvanNoronha-TomTom** [comment]
Wow thanks for the fast response! Much appreciated.
Yes indeed the r6g and t4g are ARM64 based processors. AWS tries to push adopting newer instance types by keeping their prices lower than the previous gen(t3 or c5) so I can imagine more usage in the future.

The server is question is a development instance so I can wait for the fix. Thanks!

**Comment by jcjorel** [comment]
Hi,
v0.13.1 released.
Please restart your conversion with the same options: It should complete the conversion.
Please let me know!

**Comment by jcjorel** [comment]
Hi,
v0.13.1 released.
By restarting your conversion with the same options, it should complete the conversion.
Please let me know!

**Comment by IvanNoronha-TomTom** [comment]
```
:~/spotCoverter# ./ec2-spot-converter --stop-instance --review-conversion-result --instance-id i-08da23413cc50235a
[INFO] 2021-08-30 09:49:02,476 ec2-spot-converter - [STEP 1/26] Read DynamoDB state table...
[INFO] 2021-08-30 09:49:02,535 ec2-spot-converter -   => SUCCESS. Record 'i-08da23413cc50235a' read succesfully.
[INFO] 2021-08-30 09:49:02,658 ec2-spot-converter - [STEP 2/26] Discover instance state... : RECOVERED STATE. SKIPPED!
[INFO] 2021-08-30 09:49:02,658 ec2-spot-converter -   => SUCCESS. Instance is in state running...
...
[INFO] 2021-08-30 09:49:12,495 ec2-spot-converter - [STEP 24/26] Untag resources...
[INFO] 2021-08-30 09:49:12,645 ec2-spot-converter -   => SUCCESS. Successfully untagged ['i-0700bda96f1ea1bb6', 'eni-0315f33b44b37eade'].
[INFO] 2021-08-30 09:49:12,676 ec2-spot-converter - [STEP 25/26] Waiting for instance to be at expected states in target groups... => SKIPPED! Need '--wait-for-tg-states' argument.
[INFO] 2021-08-30 09:49:12,676 ec2-spot-converter - [STEP 26/26] Deregister image... => SKIPPED! Need '--delete-ami' argument.
[INFO] 2021-08-30 09:49:12,676 ec2-spot-converter - Conversion successful! New instance id: i-0700bda96f1ea1bb6, ElapsedTime: 93052 seconds
2 files to edit

```

Worked like a charm!
Tags for the instance and storage are also copied. As well the role assigned.

Thanks for the help and fix!

**Comment by jcjorel** [comment]
Nice!
Can you give a 'star' to the project plz? 😉

**Comment by IvanNoronha-TomTom** [comment]
Sure. Done😄
