### ISSUE TITLE
error deregistering image (--delete-ami)

### ISSUE THREAD

**Issue by rafaeltuelho** [jcjorel/ec2-spot-converter#14]
Getting this error when using `--delete-ami`

```
[INFO] 2023-06-05 12:31:49,365 ec2-spot-converter - [STEP 22/26] Reboot new instance (if needed and requested)... 
[INFO] 2023-06-05 12:31:49,365 ec2-spot-converter -   => SUCCESS. No reason to reboot instance 'i-0113bca587b7f5c14'... Skipping...
[INFO] 2023-06-05 12:31:49,568 ec2-spot-converter - [STEP 23/26] Update CloudWatch alarms... => SKIPPED! Need '--update-cw-alarms' argument.
[INFO] 2023-06-05 12:31:49,568 ec2-spot-converter - [STEP 24/26] Untag resources... 
[INFO] 2023-06-05 12:31:49,870 ec2-spot-converter -   => SUCCESS. Successfully untagged ['i-0113bca587b7f5c14', 'eni-0e2f07f1dbb86ca46'].
[INFO] 2023-06-05 12:31:50,102 ec2-spot-converter - [STEP 25/26] Waiting for instance to be at expected states in target groups... => SKIPPED! Need '--wait-for-tg-states' argument.
[INFO] 2023-06-05 12:31:50,102 ec2-spot-converter - [STEP 26/26] Deregister image... 
Traceback (most recent call last):
  File "/Users/rsoares/dev/github/rafaeltuelho/sno-for-100/.run/ec2-spot-converter", line 1621, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/Users/rsoares/dev/github/rafaeltuelho/sno-for-100/.run/ec2-spot-converter", line 1587, in main
    return_code, reason, keys = step["Function"]()
                                ^^^^^^^^^^^^^^^^^^
  File "/Users/rsoares/dev/github/rafaeltuelho/sno-for-100/.run/ec2-spot-converter", line 1212, in deregister_image
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rsoares/dev/github/rafaeltuelho/sno-for-100/.run/ec2-spot-converter", line 1212, in <listcomp>
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
                ~~~^^^^^^^
KeyError: 'Ebs'
```

**Comment by TakashiKyoto** [comment]
hello does the tool still work as of october 2024 ?

**Comment by frakon** [comment]
Update NOVEMBER 2024:

**The Tool WORKS PERFECTLY upto STEP 25/26.** Without the option '--delete-ami' it works fully (through out all steps). If the option '--delete-ami' is specified, it throws an error in STEP 26/26 and does not open the changed machine json state for comparison. But the machine is completely converted, only the AMI image must be deleted manually.

The still received error if '--delete-ami' is specified:
```
ec2-spot-converter - [STEP 26/26] Deregister image...
Traceback (most recent call last):
  File "/home/ubuntu/./ec2-spot-converter", line 1621, in <module>
    sys.exit(main(sys.argv))
  File "/home/ubuntu/./ec2-spot-converter", line 1587, in main
    return_code, reason, keys = step["Function"]()
  File "/home/ubuntu/./ec2-spot-converter", line 1212, in deregister_image
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
  File "/home/ubuntu/./ec2-spot-converter", line 1212, in <listcomp>
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
KeyError: 'Ebs'

```

**Comment by jcjorel** [comment]
Hi,Thanks for the pb report.Could you describe the kind of instance converted? (Instance type and especially storage connected to it)Thanks.Envoyé de mon mobile.Le 18 nov. 2024 à 10:27, frakon ***@***.***> a écrit :﻿
Update NOVEMBER 2024:
The Tool WORKS PERFECTLY upto STEP 25/26. Without option --delete-ami it works fully (through out all steps). If the option --delete-ami is specified, it throws an error in STEP 26/26 and does not open the changed machine json state for comparison. But the machine is completely converted, only the AMI image must be deleted manually.
The still received error:
ec2-spot-converter - [STEP 26/26] Deregister image...
Traceback (most recent call last):
  File "/home/ubuntu/./ec2-spot-converter", line 1621, in <module>
    sys.exit(main(sys.argv))
  File "/home/ubuntu/./ec2-spot-converter", line 1587, in main
    return_code, reason, keys = step["Function"]()
  File "/home/ubuntu/./ec2-spot-converter", line 1212, in deregister_image
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
  File "/home/ubuntu/./ec2-spot-converter", line 1212, in <listcomp>
    snap_ids = [blk["Ebs"]["SnapshotId"] for blk in img["BlockDeviceMappings"]]
KeyError: 'Ebs'

**Comment by frakon** [comment]
Hello, further info:
* instance types: m5zn.metal -> c5a.4xlarge (spot -> spot)
* volume info: 
  * RootDeviceType: EBS
  * EBS Optimization: Disabled
  * Type: gp2
  * Size: 200 MB
  * IOPS: 600

**Comment by jcjorel** [comment]
Hi,

Could you send me the JSON content of the column 'ConversionStartInstanceState' of the DynamoDB table named 'ec2-spot-converter-state-table' and located in the row describing the context of the instance ID you are trying to convert?

Thank you.
