### ISSUE TITLE
region not specified error

### ISSUE THREAD

**Issue by regevbr** [jcjorel/ec2-spot-converter#2]
When trying to run the tool, I get an exception:
```sh
> ./ec2-spot-converter --generate-dynamodb-table
Traceback (most recent call last):
  File "./ec2-spot-converter", line 58, in <module>
    ec2_client               = boto3.client("ec2",               config=config)
  File "/usr/lib/python3.6/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/lib/python3.6/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/lib/python3.6/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/lib/python3.6/site-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/usr/lib/python3.6/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/lib/python3.6/site-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/lib/python3.6/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/lib/python3.6/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

Need to add to readme an explanation on how to configure it (you can see the options [here](https://stackoverflow.com/questions/40377662/boto3-client-noregionerror-you-must-specify-a-region-error-only-sometimes))

**Comment by regevbr** [comment]
Oh, and awesome tool saved my ass thanks @jcjorel :-)

**Comment by regevbr** [comment]
Also worth mentioning the in the diff view, the volume id of the root volume is changed as well.
I will create a PR soon to address both issues soon

**Comment by jcjorel** [comment]
Hi,
Thanks for your interest in this tool. 
FYI, I release v0.8.2 that contains a minor fix to display guidance toward users about AWS region setting. This is a common behavior of all boto3 based SW but, indeed, it can help people that are not used with this AWS ecosystem.

**Comment by regevbr** [comment]
cool thanks @jcjorel

**Comment by regevbr** [comment]
@jcjorel Also worth mentioning the in the diff view, the volume id of the root volume is changed as well (got me worried for a second when I saw it)

**Comment by jcjorel** [comment]
@regevbr Just updated the README.md. See update there: https://github.com/jcjorel/ec2-spot-converter/commit/e67c6409a5a65d505381a30ff1f789fbeb61cb37

**Comment by regevbr** [comment]
@jcjorel perfect thanks!
